site_name: Luna Docs
theme:
  name: readthedocs
  navigation_depth: 4
  collapse_navigation: false

nav:
  - Home: index.md
  - User guide: user-guide.md
  - Core:
      - Agent Format: core/agent-format.md
      - Extension Format: core/extension-format.md
      - Agents:
          - Overview: core/agents/README.md
          - Basic hierarchical: core/agents/basic-hierarchical.md
      - Agent helpers:
          - Light schema: core/agent-helpers/light-schema.md
